import { ObjectId } from 'mongodb';

/**
 * Represents a user in the system
 * Based on the schema defined in database-schema.md
 */
export interface User {
  _id: ObjectId;
  username: string;     // Indexed, Unique
  email?: string;       // Indexed, Unique (when provided)
  password_hash: string;
  createdAt: Date;
  updatedAt: Date;
  profilePicture?: string;
}

/**
 * Type for creating a new user document
 * Omits the _id field which is generated by MongoDB
 */
export type UserCreate = Omit<User, '_id'>;

/**
 * Type for updating a user document
 * All fields are optional except updatedAt
 */
export type UserUpdate = Partial<Omit<User, '_id' | 'createdAt'>> & {
  updatedAt: Date;
};

/**
 * Represents a filter for querying users
 */
export interface UserFilter {
  _id?: ObjectId;
  username?: string | RegExp;
  email?: string | RegExp;
} 